# Assignment 03 - Numpy

Answer the following questions. For each question, use the code cell below to write your solution.

## Question 1

Create a 2D Numpy array with shape (3, 3) containing random integers between 1 and 20.

In [2]:
import numpy as np
my_array=np.random.randint(1,20,size=(3,3))
print(my_array)

[[ 4 15 15]
 [10  1  6]
 [ 1  3 18]]


## Question 2

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values for each row.

In [ ]:
import numpy as np
my_array1=np.random.uniform(0,100,size=(5,5))
print(my_array1)
for i in my_array1:
    print(f"the mininum is {min(i)} the mmaximum is {max(i)} ")

[[96.21009422 94.26300993 99.73533088 40.01400996  9.41449388]
 [18.78657321 67.6322447  89.00393245 25.0589334  46.55226697]
 [64.63443603 37.04577535 47.02880285 86.70251334 43.29582602]
 [75.34696098 55.63070545 34.75476813 16.52995945 66.65459271]
 [26.34261264  8.86464362 86.83338757  3.60499074 96.33503895]]
the mininum is 9.414493880055986 the mmaximum is 99.73533088046776 
the mininum is 18.786573211992486 the mmaximum is 89.00393245146458 
the mininum is 37.045775350834454 the mmaximum is 86.70251334082867 
the mininum is 16.529959454192966 the mmaximum is 75.34696098116174 
the mininum is 3.604990736738267 the mmaximum is 96.33503894504932 


## Question 3

Write a NumPy program to create a random vector of size 10 and sort it.

In [14]:
import numpy as np

vec = np.random.rand(10)

sorted_vec = np.sort(vec)

print("Random vector is ", vec)
print("Sorted vector is", sorted_vec)


Random vector is  [0.66348504 0.22530321 0.15142704 0.60217224 0.76192598 0.35579735
 0.46153624 0.69151371 0.2216451  0.45679532]
Sorted vector is [0.15142704 0.2216451  0.22530321 0.35579735 0.45679532 0.46153624
 0.60217224 0.66348504 0.69151371 0.76192598]


## Question 4

Write a NumPy program to find the most frequent value in an array.

In [13]:
import numpy as np
from scipy import stats

arr = np.array([1, 3, 2, 5, 2, 3, 5, 4, 1, 3,5,6,5])

value = stats.mode(arr, keepdims=True)


print("Most frequent value is", value.mode[0])

Most frequent value is 5


## Question 5

Replace all even numbers in the 2D array with 0.

In [17]:
arr=np.array([[4,9,16],[25,48,87],[7,9,8]])
arr[arr % 2 == 0] = 0
print(arr)
        


[[ 0  9  0]
 [25  0 87]
 [ 7  9  0]]


## Question 6

Apply the square root function to each element of the 1D array.

In [23]:
my_array=np.array([4,9,16,25,49])
res=np.sqrt(my_array)
print(res)


[2. 3. 4. 5. 7.]


## Question 7

Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [ ]:
from numpy import *
my_array=np.random.random((3,3))
print(my_array)
for i in my_array:
    res=subtract(i,mean(i))
    print(f"the mean of each row is {res}")

[[0.04606015 0.52627333 0.00419895]
 [0.8962528  0.05140646 0.12614682]
 [0.08879064 0.73214906 0.79878233]]
the mean of each row is [-0.14611733  0.33409585 -0.18797852]
the mean of each row is [ 0.53831744 -0.3065289  -0.23178854]
the mean of each row is [-0.4511167   0.19224172  0.25887498]


## Question 8

Create a 1D array containing the first 20 odd numbers.

In [3]:
import numpy as np
arr=np.arange(1,40,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


## Question 9

Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [9]:
import numpy as np
arr=np.random.randint(1,100,size=(5,5))
sorted=np.sort(arr,axis=0)
print(sorted)
second=sorted[-2,:]
print("Second largest value in each column:", second)


[[ 9 49 12  6 15]
 [13 58 19 28 83]
 [49 71 29 34 93]
 [51 80 43 57 93]
 [72 94 71 81 96]]
Second largest value in each column: [51 80 43 57 93]


## Question 10

Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [22]:
from numpy import *
my_array=np.random.random((4,4))
print(my_array)
for i in my_array:
    
    res=sum(i)
    print(f"the sum of each row is {res}")


[[0.25383465 0.4280709  0.76408261 0.16393513]
 [0.15807519 0.33040747 0.74514895 0.21982824]
 [0.47762353 0.44075721 0.89773586 0.89666113]
 [0.48003036 0.10637131 0.04977046 0.19691951]]
the sum of each row is 1.6099232987994372
the sum of each row is 1.453459845160244
the sum of each row is 2.7127777272495965
the sum of each row is 0.8330916358027691
