In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
print(np.__version__)

2.1.3


In [7]:
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
print(my_array)
print(my_list)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [8]:
print(type(my_array))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
a=np.array(10)
b=np.array([10,20])#one d array
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d[1][1][2])

6


In [12]:
print(d[0][1][0])

4


In [13]:
print(c[0][1])

2


In [14]:
print(a.ndim)#numbr of dimn

0


In [15]:
print(b.ndim)

1


In [16]:
print(c.ndim)

2


In [17]:
print(d.ndim)

3


In [22]:
my_array2=np.array([1,2,3],ndmin=3)

In [23]:
print(my_array2.ndim)

3


In [24]:
print(my_array2)

[[[1 2 3]]]


In [25]:
print(my_array2[0])

[[1 2 3]]


In [30]:
print(my_array2[0][0][1])

2


In [32]:
print(id(my_list[0]))

140725390128040


In [33]:
print(id(my_array[0]))

1917842326384


In [34]:
print(id(my_list[1]))

140725390128072


In [35]:
print(id(my_array[1]))

1917842333616


In [44]:
my_list3=[1,2,'a','b']
my_array3=np.array(my_list3)
print(type(my_list3[0]))

<class 'int'>


In [45]:
print(type(my_array3[0]))

<class 'numpy.str_'>


In [46]:
my_list3=[1,2,'a','b']
my_array3=np.array([1,2])
print(type(my_list3[0]))

<class 'int'>


In [47]:
print(type(my_array3[0]))

<class 'numpy.int64'>


In [8]:
import numpy as np
import time
import sys
elements =150
mylist1=range(elements)
mylist2=range(elements)
myarray=np.arange(elements)

In [6]:
print(myarray)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


In [7]:
print(mylist)

range(0, 150)


In [10]:
for n1,n2 in zip(mylist1,mylist2):
    print(n1+n2)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298


In [12]:
list_resolt=[(n1+n1) for n1,n2 in zip(mylist1,mylist2)]
print(list_resolt)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298]


In [13]:
myarray=np.arange(100)
print(myarray)
print(myarray.size)
print(myarray.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
100
8


In [14]:
print(f"{myarray.size*myarray.itemsize}")

800


In [16]:
a=np.array(["a","b","c","d","e","f"])
print(a.ndim)


1


In [17]:
b=np.array([["a","b","x"],["c","d","y"],["e","f","z"]])
print(b.ndim)

2


In [18]:
print(b[0][0])

a


In [19]:
import numpy as np
my_array=np.array([1,2,3])
my_array2=np.array([1.2,3.4,7.8])
my_array3=np.array(["sana","sama","samar"])

In [20]:
print(my_array.dtype)

int64


In [21]:
print(my_array2.dtype)

float64


In [22]:
print(my_array3.dtype)

<U5


In [39]:
#my_array4=np.array([1,2,3],dtype="f")#f32
#my_array4=np.array([1,2,3],dtype="float")
my_array4=np.array([1,2,3],dtype=float)

my_array5=np.array([1.2,3.4,7.8],dtype='i')#or int or "int"=64
my_array6=np.array(["sana","sama","samar"])


In [37]:
print(my_array4.dtype)

float64


In [38]:
print(my_array5.dtype)

int32


In [52]:
my_array7=np.array([1,2,3,4,0,6])
print(my_array7.dtype)

int64


In [53]:
my_array7=my_array7.astype("bool")#change existing array

In [54]:
print(my_array7.dtype)

bool


In [55]:
print(my_array7)

[ True  True  True  True False  True]


In [60]:
my_array8=np.array([1,2,3])
my_array9=np.array([4,5,6])
print(my_array8+my_array9)

[5 7 9]


In [61]:
my_array10=np.array([[1,2],[3,4]])
my_array11=np.array([[6,8],[6,5]])
print(my_array10+my_array11)

[[ 7 10]
 [ 9  9]]


In [63]:
print(my_array8.min())

1


In [64]:
print(my_array10.min())

1


In [65]:
print(my_array8.sum())

6


In [66]:
print(my_array10.sum())

10


#ravel

In [68]:
my_array10=np.array([[1,2],[3,4]])
print(my_array10.ravel())#return to 1 dimn

[1 2 3 4]


In [69]:
my_array10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


In [70]:
print(my_array10.ravel())#return to 1 dimn

[1 2 3 4 5 6 7 8]


In [71]:
my_array8=np.array([1,2,3])
print(my_array8.ndim)
print(my_array8.shape)#number of elements


1
(3,)


In [72]:
my_array10=np.array([[1,2],[3,4]])
print(my_array10.ndim)
print(my_array10.shape)#number of elements


2
(2, 2)


In [75]:
my_array10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(my_array10.ndim)
print(my_array10.shape)

3
(2, 2, 2)
