In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [4]:
np.save("arr_num.npy",a)

In [5]:
arr=np.load("arr_num.npy")

In [6]:
arr

array([1, 2, 3])

#pandas

In [7]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [8]:
import pandas as pd


In [9]:
x={
    "name":["sana","ahmed"],
    "age":[20,90],
    "course":["ai","cs"]
}

In [10]:
x["name"]

['sana', 'ahmed']

In [11]:
df=pd.DataFrame(x,index=["one","two"])

In [12]:
df

,name,age,course
one,sana,20,ai
two,ahmed,90,cs


In [13]:
df["name"]

one     sana
two    ahmed
Name: name, dtype: object

In [14]:
df=pd.DataFrame({
    "name":["sana","ahmed"],
    "age":[20,90],
    "course":["ai","cs"]
},index=["one","two"])

In [15]:
df

,name,age,course
one,sana,20,ai
two,ahmed,90,cs


In [16]:
df.iloc[0]

name      sana
age         20
course      ai
Name: one, dtype: object

In [17]:
df.loc["one"]

name      sana
age         20
course      ai
Name: one, dtype: object

In [18]:
df=pd.DataFrame({
    "name":["sana","ahmed","ali","soo"],
    "age":[20,90,80,90],
    "course":["ai","cs","bi","html"]
})

In [19]:
df

,name,age,course
0,sana,20,ai
1,ahmed,90,cs
2,ali,80,bi
3,soo,90,html


In [20]:
df["age"].unique()

array([20, 90, 80])

In [21]:
df["age"].value_counts()

age
90    2
20    1
80    1
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   course  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [23]:
df.describe()

,age
count,4.000000
mean,70.000000
std,33.665016
min,20.000000
25%,65.000000
50%,85.000000
75%,90.000000
max,90.000000


In [24]:
df["age"]>80

0    False
1     True
2    False
3     True
Name: age, dtype: bool

In [25]:
df[df["age"]>80]

,name,age,course
1,ahmed,90,cs
3,soo,90,html


In [26]:
df.rename({"name":"name_stu"},axis=1,inplace=True)

In [27]:
df

,name_stu,age,course
0,sana,20,ai
1,ahmed,90,cs
2,ali,80,bi
3,soo,90,html


In [28]:
df.sort_values("age",inplace=True)

In [29]:
df

,name_stu,age,course
0,sana,20,ai
2,ali,80,bi
1,ahmed,90,cs
3,soo,90,html


In [30]:
df.reset_index(inplace=True)

In [31]:
df

,index,name_stu,age,course
0,0,sana,20,ai
1,2,ali,80,bi
2,1,ahmed,90,cs
3,3,soo,90,html


In [32]:
df.drop(columns=["index"])

,name_stu,age,course
0,sana,20,ai
1,ali,80,bi
2,ahmed,90,cs
3,soo,90,html


In [33]:
df["salary"]=[300,400,600,700]


In [34]:
df

,index,name_stu,age,course,salary
0,0,sana,20,ai,300
1,2,ali,80,bi,400
2,1,ahmed,90,cs,600
3,3,soo,90,html,700


In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   index     4 non-null      int64 
 1   name_stu  4 non-null      object
 2   age       4 non-null      int64 
 3   course    4 non-null      object
 4   salary    4 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 292.0+ bytes


In [36]:
df.course=df.course.replace("ai","html")

In [37]:
df


,index,name_stu,age,course,salary
0,0,sana,20,html,300
1,2,ali,80,bi,400
2,1,ahmed,90,cs,600
3,3,soo,90,html,700


In [38]:
df

,index,name_stu,age,course,salary
0,0,sana,20,html,300
1,2,ali,80,bi,400
2,1,ahmed,90,cs,600
3,3,soo,90,html,700


In [39]:
df=pd.read_csv("Iris.csv")

In [40]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [42]:
df.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [43]:
len(df)#num of rows

150

In [44]:
df.shape

(150, 6)

In [45]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [46]:
df.head(6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa


In [47]:
df.tail(6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica


In [48]:
df.isnull()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
145,False,False,False,False,False,False
146,False,False,False,False,False,False
147,False,False,False,False,False,False
148,False,False,False,False,False,False


In [49]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [51]:
df.Species#num of classes

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [52]:
df.Species.unique()#num of classes

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [53]:
df.Species.value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [54]:
len(df)

150

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [57]:
df.drop_duplicates(keep="last",inplace=True)#version

In [58]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [59]:
df.drop(columns=["Id"],inplace=True)

In [60]:
df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [61]:
df=pd.read_csv("student_scores.csv")

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes


In [63]:
df

,Hours,Scores
0,2.5,21
1,5.1,47
2,3.2,27
3,8.5,75
4,3.5,30
5,1.5,20
6,9.2,88
7,5.5,60
8,8.3,81
9,2.7,25


In [64]:
df.head()

,Hours,Scores
0,2.5,21
1,5.1,47
2,3.2,27
3,8.5,75
4,3.5,30


In [65]:
df.tail()

,Hours,Scores
20,2.7,30
21,4.8,54
22,3.8,35
23,6.9,76
24,7.8,86


In [66]:
df.isnull()

,Hours,Scores
0,False,False
1,False,False
2,False,False
3,False,False
4,False,False
5,False,False
6,False,False
7,False,False
8,False,False
9,False,False


In [67]:
df.isnull().sum()

Hours     0
Scores    0
dtype: int64

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes


In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df.drop_duplicates(keep="last",inplace=True)#version

## sana

In [71]:
df.Scores.value_counts()

Scores
30    3
47    1
21    1
27    1
75    1
20    1
88    1
60    1
81    1
25    1
85    1
62    1
41    1
42    1
17    1
95    1
24    1
67    1
69    1
54    1
35    1
76    1
86    1
Name: count, dtype: int64

In [72]:
df=pd.DataFrame({
    "name":["sana","ahmed","ali","wael"],
    "age":[20,90,50,38],
    "course":["ai","cs","bio","re"]
})

In [73]:
import numpy as np

In [74]:
df["bonus"]=np.random.randint(100,300000,size=len(df))

In [75]:
df

,name,age,course,bonus
0,sana,20,ai,173622
1,ahmed,90,cs,121378
2,ali,50,bio,162085
3,wael,38,re,192637


In [76]:
df.bonus.cumsum()

0    173622
1    295000
2    457085
3    649722
Name: bonus, dtype: int64

In [77]:
df.bonus.cummax()

0    173622
1    173622
2    173622
3    192637
Name: bonus, dtype: int32

In [78]:
df.bonus.cummin()

0    173622
1    121378
2    121378
3    121378
Name: bonus, dtype: int32

In [79]:
df["cummin"]=df.bonus.cummin()

In [80]:
df

,name,age,course,bonus,cummin
0,sana,20,ai,173622,173622
1,ahmed,90,cs,121378,121378
2,ali,50,bio,162085,121378
3,wael,38,re,192637,121378


In [81]:
df=df[["name","cummin"]]

In [82]:
df

,name,cummin
0,sana,173622
1,ahmed,121378
2,ali,121378
3,wael,121378


In [83]:
df.to_csv("Employee Data.csv")

In [84]:
melt_df=pd.melt(df)

In [85]:
melt_df

,variable,value
0,name,sana
1,name,ahmed
2,name,ali
3,name,wael
4,cummin,173622
5,cummin,121378
6,cummin,121378
7,cummin,121378


In [86]:
melt_df.head()

,variable,value
0,name,sana
1,name,ahmed
2,name,ali
3,name,wael
4,cummin,173622


In [90]:
pivot_df=melt_df.pivot(columns="variable",values="value")

In [91]:
pivot_df

variable,cummin,name
0,NaN,sana
1,NaN,ahmed
2,NaN,ali
3,NaN,wael
4,173622,NaN
5,121378,NaN
6,121378,NaN
7,121378,NaN


In [89]:
melt_df.head()

,variable,value
0,name,sana
1,name,ahmed
2,name,ali
3,name,wael
4,cummin,173622


In [93]:
melt_df["index"]=melt_df.groupby("variable").cumcount()

In [94]:
melt_df

,variable,value,index
0,name,sana,0
1,name,ahmed,1
2,name,ali,2
3,name,wael,3
4,cummin,173622,0
5,cummin,121378,1
6,cummin,121378,2
7,cummin,121378,3


In [96]:
pivot_df=melt_df.pivot(index="index",columns="variable",values="value")

In [97]:
pivot_df=melt_df.pivot(columns="variable",values="value")

variable,cummin,name
index,,
0,173622,sana
1,121378,ahmed
2,121378,ali
3,121378,wael


In [98]:
pivot_df.reset_index(inplace=True)

In [99]:
pivot_df

variable,index,cummin,name
0,0,173622,sana
1,1,121378,ahmed
2,2,121378,ali
3,3,121378,wael


In [107]:
pivot_df.drop(columns=["index"],inplace=True)

In [108]:
pivot_df

variable,cummin,name
0,173622,sana
1,121378,ahmed
2,121378,ali
3,121378,wael


In [109]:
pivot_df.columns

Index(['cummin', 'name'], dtype='object', name='variable')

In [111]:
pivot_df.columns.name=None

In [112]:
pivot_df

,cummin,name
0,173622,sana
1,121378,ahmed
2,121378,ali
3,121378,wael


In [113]:
pivot_df.sample()

,cummin,name
3,121378,wael


In [114]:
pivot_df.query(('name=="sana"'))

,cummin,name
0,173622,sana
